name: Tests

on: [pull_request, push]

jobs:
    tests:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php_version: ['7.2', '7.3', '7.4', '8.0']

        steps:
            -   run: composer require phpstan/phpstan --dev
            -   run: composer require phpstan/extension-installer --dev

            # get current dev-main version
            -   run: composer require symplify/phpstan-rules:@dev --dev

            -   run: vendor/bin/phpstan analyze src --config phpstan-for-tests.neon
